# Generated by Django 3.2.16 on 2022-10-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeslot', models.CharField(choices=[(1, '17:30'), (2, '18:00'), (3, '18:30'), (4, '19:00'), (5, '19:30'), (6, '20:00'), (7, '20:30'), (8, '21:00'), (9, '21:30'), (10, '22:00')], max_length=6)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to='restaurantapp.costumer')),
            ],
        ),
    ]
