# Generated by Django 3.2.16 on 2022-10-25 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationNoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('date', models.DateField(verbose_name='Date')),
                ('number_of_people', models.IntegerField(verbose_name='Number of Guests')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeslot', models.CharField(choices=[('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00')], max_length=8, verbose_name='Time')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Anything else? (Allergies, Special Dietary Wishes,...)')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('number_of_people', models.IntegerField(verbose_name='Number of Guests')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeslot', models.CharField(choices=[('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00')], max_length=8, verbose_name='Time')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Anything else? (Allergies, Special Dietary Wishes,...)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
    ]
