# Generated by Django 3.2.16 on 2022-10-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationnouser',
            name='lname',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
