# Generated by Django 3.2.16 on 2022-10-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_auto_20221012_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reservation',
        ),
    ]
