# Generated by Django 3.2.16 on 2022-10-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
