# Generated by Django 3.2.16 on 2022-10-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_reservation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'get_latest_by': 'date'},
        ),
    ]
