# Generated by Django 3.2.16 on 2022-10-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0006_alter_reservation_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
