# Generated by Django 3.2.16 on 2022-10-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0008_reservation_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='costumer',
        ),
        migrations.DeleteModel(
            name='Costumer',
        ),
    ]
