# Generated by Django 3.2.16 on 2022-10-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0011_auto_20221018_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
